# Generated by Django 3.0.5 on 2020-04-20 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_remove_member_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('task', models.CharField(max_length=300)),
                ('members', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Member')),
            ],
        ),
    ]
