# Generated by Django 3.0.5 on 2020-04-20 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20200419_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('A', 'assigned'), ('P', 'in progress'), ('C', 'completed')], default='A', max_length=100),
        ),
    ]
