# Generated by Django 3.0.5 on 2020-04-20 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('A', 'assigned'), ('P', 'in progress'), ('C', 'completed')], default='A', max_length=1),
        ),
    ]
