# Generated by Django 3.0.5 on 2020-04-21 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20200420_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('A', 'Assigned'), ('P', 'In Progress'), ('C', 'Completed')], default='A', max_length=1),
        ),
    ]
